name: 'build with pyInstaller'

on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            TARGET: macos
            CMD_BUILD: >
              pyinstaller -F -w -n priceComparison -i resources/priceComparison.icns gui.py &&
              cd dist/ &&
              zip -r9 priceComparison priceComparison.app/
            OUT_FILE_NAME: priceComparison.zip
            # dont know what that does
            # ASSET_MIME: application/zip
          - os: windows-latest
            TARGET: windows
            CMD_BUILD: pyinstaller -F -w -n priceComparison -i resources/priceComparison.ico gui.py
            OUT_FILE_NAME: priceComparison.exe
            # dont know what that does
            #ASSET_MIME: application/vnd.microsoft.portable-executable
          - os: ubuntu-latest
            TARGET: linux
            CMD_BUILD: pyinstaller -F -w -n priceComparison -i resources/priceComparison.ico gui.py
            OUT_FILE_NAME: priceComparison.deb
            # dont know what that does
            #ASSET_MIME: application/vnd.microsoft.portable-executable

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: 3.11

    - run: pip install -r requirements.txt pyinstaller
    - run: pyinstaller --onefile gui.py
    # Optionally verify that it works (provided that it does not need user interaction)
    # - run: ./dist/gui
    - uses: actions/upload-artifact@v3
      with:
        path: dist/*
